// <auto-generated />
namespace Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class regex_gradovi2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(regex_gradovi2));
        
        string IMigrationMetadata.Id
        {
            get { return "202509262256527_regex_gradovi2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
