// <auto-generated />
namespace Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class total_pricr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(total_pricr));
        
        string IMigrationMetadata.Id
        {
            get { return "202509281320434_total_pricr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
