// <auto-generated />
namespace Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class kopija : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kopija));
        
        string IMigrationMetadata.Id
        {
            get { return "202509261432126_kopija"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
